### PR TITLE
Use file path to lint template

### LINKED ISSUE #1161: Does ember-template-lint v2 support ESLint integration?
Looking at upgrading to v2 and ran into an ESLint issue on the following code:

```typescript
import hbs from "htmlbars-inline-precompile"

hbs`<MyComponent />`
```

which gives the following output when running ESLint:

`
3:1  error  3 error(s): The "path" argument must be of type string. Received type undefined  hbs/check-hbs-template-literals
`

Is the ESLint integration intended to work with v2 yet? I did notice
`warning " > eslint-plugin-hbs@1.0.0" has incorrect peer dependency "ember-template-lint@^1.5.3".` when installing, so perhaps this isn't supported yet.

My `.template-lintrc.js` is:

```javascript
module.exports = {
  extends: ["recommended", "octane", "stylistic"],

  rules: {
    "attribute-indentation": false,
    "eol-last": "always",
    "inline-link-to": true,
    "modifier-name-case": true,
    "no-bare-strings": true,
    "no-implicit-this": { allow: ["rootURL"] },
    "no-invalid-interactive": false,
    "require-valid-alt-text": false,
    "template-length": { max: 275, min: 1 }
  }
}
```

Thanks!

### PR DESCRIPTION
**Pull request by bobisjan**
This PR fixes error `The "path" argument must be of type string. Received type undefined` introduced by this [fix](https://github.com/ember-template-lint/ember-template-lint/pull/1072) 🙈.

fixes ember-template-lint/ember-template-lint#1161

### CODE REVIEW

File: lib/rules/check-hbs-template-literals.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ module.exports = {
           if (node.quasi.type === 'TemplateLiteral') {
             let hbs = node.quasi.quasis[0].value.cooked
             hbs = unindentAndStripSafeNewlines(hbs)
-            const results = linter.verify({source: hbs.toString(), moduleId: context.id})
+            const results = linter.verify({source: hbs.toString(), filePath: context.id, moduleId: context.id})
```
Comment (jaydgruber) [inline lib/rules/check-hbs-template-literals.js:78]:
```suggestion
            const results = linter.verify({source: hbs.toString(), filePath: context.id, moduleId: context.getFilename()})
```

based on [eslint docs](https://eslint.org/docs/4.0.0/developer-guide/working-with-rules#the-context-object), `context.id` seems like the wrong thing here.

**Comment by jaydgruber** [comment]
I think this would resolve #40 w/ the suggested change.

File: lib/rules/check-hbs-template-literals.js (hunk 1 above)
Comment (dfreeman) [reply lib/rules/check-hbs-template-literals.js:78]: It's a shame this was merged without this fix; I just hit #40 as well and came to the same conclusion—`context.id` is just the rule name `check-hbs-template-literals`, which doesn't really make sense as the `filePath` or `moduleId`
